name: Version

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    name: Version bump

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          majorList: "!,feat!"
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent
          branch: main

      - name: Create tag
        uses: actions/github-script@v5
        if: ${{ steps.semver.outputs.next }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next }}',
              sha: context.sha
            })