name: Version

on:
  push:
    branches:
      - main

jobs:
  version-bump:
    runs-on: ubuntu-latest
    name: Version bump

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1.8.0
        with:
          token: ${{ github.token }}
          majorList: "!,feat!"
          noVersionBumpBehavior: silent
          noNewCommitBehavior: silent
          branch: main

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.semver.outputs.next }}
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}